kind: pipeline
name: default

steps:
- name: test
  image: jupyter/scipy-notebook
  pull: always
  commands:
  - /bin/bash script/setup.sh
  - python -m unittest discover -v -s ./test
- name: integration test
  image: jupyter/scipy-notebook
  pull: always
  volumes:
    - name: data
      path: data
  commands:
  - /bin/bash script/setup.sh
  - python -m unittest discover -s ./test -p "integration*.py"

volumes:
- name: data
  host:
    path: /home/andreas/projects/motiv/data